apiVersion: app/v1
kind: Deployment
metadata:
  name; worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  templete:  
    metadata:
	  labels:
	    component: worker
    spec:
      containers:
	    - name: worker
	      image: salahkhaled101/multi-worker
          env:
		    - name: REDIS_HOST
			  value: redis-cluster-ip-service
			- name: REDIS_PORT
			  value: '6379'